version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    image: jyongz/nod-project-full:mysql-8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    build:
      context: .
      dockerfile: Dockerfile.phpmyadmin
    image: jyongz/nod-project-full:phpmyadmin-latest
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      PMA_USER: myuser
      PMA_PASSWORD: mypassword
    ports:
      - "8080:80"
    depends_on:
      - mysql

  app:
    build:
      context: ../kelompok2
      dockerfile: Dockerfile.prod
    image: jyongz/nod-project-full:app-v2
    container_name: nod-project
    ports:
      - "3000:3000"
    depends_on:
      - mysql

volumes:
  mysql_data:
    driver: local
